### ISSUE TITLE
fmount FAT Filesystem error

### ISSUE THREAD

**Issue by paloky** [maxiufeng258/SPI_Flash_Uart_Led_Polling_V1.0#1]
Hi.
I try yor library, and I have problems to mount the W25Q.

If I debug the code, I can see how the communication with the memory works correctly and identifies which memory it is.
But when I do the "fmount", I always get a "FR_NO_FILESYSTEM", and it doesn't recognize the FAT format when Check boot record signature in "check_fs" function.
How do I "format" or initialize the W25Q to identify it as FAT?

Thank's a lot.

**Comment by simon88** [comment]
Hi @paloky same issue for me, have resolved your issue ?

**Comment by paloky** [comment]
Hi @simon88  Yes, I solved the problem.
You have to format the SD card for it to be recognized.

Format the card if you get an error when mount it using the function "f_mksfs()"
**f_mkfs("0:", FM_ANY, 0, buffer, sizeof(buffer));**

Example:
`       
                
    FRESULT fres;
	FATFS fs;
	FIL   fp;
	fres = f_mount(&fs, "0:", 1);
	if (fres == FR_OK)
	{
		fres = f_open(&fp, "0:config.txt", FA_OPEN_ALWAYS|FA_READ);
                // TO DO:  read files..
                ..............
       }
       else
	{
	       // Format SD Card
		printf("mount w25qxxx flash failed...\r\n");
		static uint8_t buffer[_MAX_SS];
		fres = f_mkfs("0:", FM_ANY, 0, buffer, sizeof(buffer));
		if(fres == FR_OK){
			printf("w25qxxx Formated OK....\r\n");
		}else{
			printf("ERROR formating w25qxxx....\r\n");
		}
	}
       // Un-Mount
       fres = f_mount(NULL, "0:", 1);
`

Best Regards.

**Comment by simon88** [comment]
Thanks a lot @paloky it's working 👍

**Comment by paloky** [comment]
👍
